### PR TITLE
First restructuring and proposal how to name the different folders..

### LINKED ISSUE #114: Restructure the pyWATTS library to pyWATTS.modules.metrics, pyWATTS.core, pyWATTS.modules.models, ...
Maybe we could restructure the pyWATTS library to pyWATTS.modules.metrics, pyWATTS.modules.core, pyWATTS.modules.models, ... to give the user some structure.

_Originally posted by @olineumann in https://github.com/KIT-IAI/pyWATTS/pull/85#discussion_r656125766_

### PR DESCRIPTION
**Pull request by benHeid**
## Related Issues
closes #114 
## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos)
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Did you update the CHANGELOG

## PR review
Anyone in the community is free to review the PR once the tests have passed.

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones to the PR so it can be classified

### CODE REVIEW

**Comment by benHeid** [comment]
@olineumann do you have other ideas for restructuring the modules

**Review by olineumann — COMMENTED** [review]
I have only some comments:
- Is it correct that rolling_rmse is in metrics and all other rolling calculations are in statistics?
- Is it maybe an option to join statistics and metrics?
- Is clock shift, resample and differentiate a preprocessing or feature extraction? IMO clock_shift und resample is more a feature extraction module?

Everything else looks good to me. :+1:

**Comment by olineumann** [comment]
> 
> 
> I have only some comments:
> 
>     * Is it correct that rolling_rmse is in metrics and all other rolling calculations are in statistics?
> 
>     * Is it maybe an option to join statistics and metrics?
> 
>     * Is clock shift, resample and differentiate a preprocessing or feature extraction? IMO clock_shift und resample is more a feature extraction module?
> 
> 
> Everything else looks good to me. 👍

Add wrappers to modules folder and join statistics and feature extraction.

**Review by olineumann — CHANGES_REQUESTED** [review]
Examples currently not working because of failing imports. Also, the `__init__.py` in pywatts/modules/ importing not existing python files. Do we want du change the `__init__.py` file and leave the examples as they are or do we want do clear the `__init__.py` and change the examples. I would prefer the second option because I think it is cleaner but the first option would be backward compatible. Additionally, we could do both: Update the `__init__.py` and the examples.

**Review by olineumann — COMMENTED** [review]
I like the new structure! I just would rename sample_module into sample.py (I would like sampler.py more but resample.py also contains Resampler class?).

**Review by olineumann — APPROVED** [review]

**Pull request merged**
